dbt_project:
  target: dev
  outputs:
    dev:
      type: databricks
      schema: default
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_ACCESS_TOKEN') }}"
