version: 2

sources:
  - name: jaffle_shop
    database: since_workspace_aws  # 使用するDatabricksのデータベース
    schema: default    # 使用するスキーマ（必要に応じて変更）
    tables:
      - name: raw_customers
        description: "Raw customer data"
      - name: raw_orders
        description: "Raw order data"
      - name: raw_payments
        description: "Raw payment data"
